### ISSUE TITLE
Verbose Option

### ISSUE THREAD

**Issue by Notsonoble** [McMustard/pf_items#8]
For the web/gui interfaces, a verbose output of rolls would be nice.

**Comment by McMustard** [comment]
I worked on this a little today. In a local branch, I have a working implementation, but it adds a bit of a delay. This is because it takes thousands of rolls to generate items for a large city. About 98% of the items generated (in the case of large city) are rejected because they fall below the base value. Even though I can throw away log entries if the item ends up being rejected, it takes too much time to compose the log entries for all those rolls. 

I don't like having such a delay, so unfortunately, I think I'll have to pass on this for now. It's a nice feature idea, but ultimately I don't think it would be worth the work it would take to properly deal with the delay (on the user interface side for good UX, and on the server side to deal with load well -- this is just a hobby for me). That said, I was considering converting over to a client-side model, and in that case, I would include the feature there.
